# Generated by Django 3.1.7 on 2021-03-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0002_auto_20210306_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
